### ISSUE TITLE
Show target framework mismatch error

### ISSUE THREAD

**Issue by VahidN** [dotnet/vscode-csharp#1724]
It would be great if this extension shows us when the new target framework is 2 and in `.vscode\launch.json` file we still have an old reference to the v1.0 
```json
"program": "${workspaceRoot}/src/Sample/bin/Debug/netcoreapp1.0/Sample.dll"
```
in this case when we start a debugging session, we will see this error message: 
```
The specified framework 'Microsoft.NETCore.App', version '1.1.2' was not found.
```
which can be eliminated just by changing the `netcoreapp1.0` to `netcoreapp2.0` in the above setting.

**Comment by gregg-miskelly** [comment]
I haven't been able to think of anything the extension can do about this. The problem is that VS Code doesn't have real project systems. So the debugger doesn't understand anything about your project -- it is just launching the file we were told to launch. In this case, there is a 'netcoreapp1.0' file, and so we try to launch it. I guess the language service side could try and scan this file, but it feels like a lot of work to me.

**Comment by DustinCampbell** [comment]
I think we might be able to move to a model where we dynamically set these properties using the information here: https://github.com/Microsoft/vscode-docs/blob/master/release-notes/v1_9.md#debugger-extension-authoring. I haven't looked too deeply at it though.

**Comment by JoeRobich** [comment]
The C# DevKit uses the Task api to generate the build tasks based on the current project system information and there is no launch.json that can become incorrect.
