### ISSUE TITLE
[Feature Request] Add an option to unload projects

### ISSUE THREAD

**Issue by harry-cpp** [dotnet/vscode-csharp#1984]
It would be nice if there was a way to unload a project. This is useful for projects which generate a lot of code(ie. .NET wrappers) since I don't want omnisharp to monitor all those files until the generation of all of them is done.

**Comment by DustinCampbell** [comment]
Thanks for the request. It's on our backlog. However, note that there's no telling when we will get to this or what shape it might take.

**Comment by sjetha-pason** [comment]
We have some legacy Silverlight projects, and rather than have to go down the route of having our DBA get a VS Professional licence just to make small tweaks to our code, we wanted to see if we could have him use VS Code instead. After deleting the Silverlight files completely from his machine we were able to make it work, but this is far from ideal.

**Comment by sjetha-pason** [comment]
Hi @TheRealPiotrP. Ideally, we would want to be able to have one solution file that gets committed to our version control system that would cover all of our scenarios. However, having a secondary SLN file that would make the loading of the projects easier for our DBA could work out. We'll give it a try and report back with any concerns or issues.
Thanks for your help.

**Comment by JoeRobich** [comment]
Closing as the C# DevKit extension would be where we added Solution manipulation functionality.

**Comment by SHiLLySiT** [comment]
For posterity, this seems to be the relevant ticket in the dev kit extension 

github.com/microsoft/vscode-dotnettools/issues/431
