### ISSUE TITLE
How can I add an COM reference into a c# proj in vscode 

### ISSUE THREAD

**Issue by shikouzhong** [dotnet/vscode-csharp#2338]
Yes, we can add a nuget package using the dotnet comand line, but I don't know how to add a COM reference in vscode, just as in vs community and is it supported in omnisharp-vscode?

I have searched the stackoverflow, but no right answer for c# proj in vscode.

-VSCode Version: 1.23.0
-OS Version: Windows 10 1803

**Comment by DustinCampbell** [comment]
It sounds like this is really a .NET project question rather than C# for VS Code. Assuming that your project targets .NET Framework, I would expect a legal `<ComReference />` in your project to just work on Windows, but I'm unsure of the level of support for them in the .NET Core SDK. If they're supported, there's certainly not a gesture to add them to the project today.

cc @livarcocc, @dsplaisted, and @nguerrera from the .NET Core SDK team.

**Comment by scyentyfyc** [comment]
A lot of time has passed since this was posted, but I found [this example using Excel via COM](https://github.com/dotnet/samples/tree/master/core/extensions/ExcelDemo), but it sounds like they were using the full VS IDE (not reference in the README to opening with devenv.exe), not VS Code.  So, I'm still chasing this issue...

**Comment by JoeRobich** [comment]
Closing as answered.
