### ISSUE TITLE
Feature Request: Use the notification panel when installing dependencies

### ISSUE THREAD

**Issue by imba-tjd** [dotnet/vscode-csharp#2814]
Just like this:
![qq 20190126164336](https://user-images.githubusercontent.com/24759802/51784823-c6bcaa00-2189-11e9-9bcc-6a18d4602880.png)
Maybe related to this: https://github.com/OmniSharp/omnisharp-vscode/issues/2717#issuecomment-443373262

I just saw another UI.

![图片](https://user-images.githubusercontent.com/24759802/64076751-43ed6600-ccfb-11e9-8c55-69934b58c622.png)

**Comment by akshita31** [comment]
@imba-tjd We deliberately add the logging information to the channels so that if there is a problem in the download the users can see the download progress and the error is clear. In #2717 we are setting the focus to the channel we are printing, hence the actual change that I think we need is not to steal the focus.

**Comment by JoeRobich** [comment]
Closing as we don't plan on making any changes in this area at this time.
