### ISSUE TITLE
Ambiquity field (I only have one field)

### ISSUE THREAD

**Issue by callmeblessed** [dotnet/vscode-csharp#2889]
Omnisharp showing: 
Ambiguity between 'ClientPersonalRepository._context' and 'ClientPersonalRepository._context' [CRSApp.API, CRSApp.API]

sometimes I got this, it said ambiquity on the same fields. I only have on _context on my class. 
Here is my code. 

`using System;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

using CRSApp.API.Helpers;
using CRSApp.API.Models.Clients;

namespace CRSApp.API.Data
{
    public class ClientPersonalRepository : IClientPersonalRepository
    {
        private readonly DataContext _context;

        public ClientPersonalRepository(DataContext context)
        {
            _context = context;
        }
        public void Add<T>(T entity) where T : class
        {
            _context.Add(entity);
        }

        public void Delete<T>(T entity) where T : class
        {
            throw new System.NotImplementedException();

        }`

**Comment by objmj-itminds** [comment]
Wanna chime in here - quite an annoying little visual issue.
I too have this issue. 

Explanation, Currently I see a lot of random 'Ambiguity' problems in the editor and not from the cli.

Here is an example problem:
`Ambiguity between 'DepartmentStockCountSignOff.DepartmentId' and 'DepartmentStockCountSignOff.DepartmentId' [data-core.API]csharp(CS0229)`

I have yet to figure out a sure way to reproduce it - but it happens when cloning a file and renaming it.

Is still there even after `dotnet clean`

![image](https://user-images.githubusercontent.com/17781340/71548435-406aa280-29ae-11ea-8cfe-af9186bc8c68.png)


Extension version: 1.21.9
VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T18:37:42.077Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled_readback<br>webgl2: enabled_readback|
|Load (avg)|undefined|
|Memory (System)|15.86GB (2.49GB free)|
|Process Argv|CODE.code-workspace|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ponchautf** [comment]
Hi,

did we can have some update about this?
This issue can back from version to version of onmisharp.

I had this issue lot of time in the past, then disapear, and now it's back again.

Cleaned project solution don't help, restarting onmisharp from command palette sometime help (but not always)

**Comment by 777LK777** [comment]
Это очень раздражает

**Comment by eric-adams-petdesk** [comment]
Boosting this - have been experiencing across .NET 6+ projects in VSCode Omnisharp

**Comment by JoeRobich** [comment]
There have been lots of improvements since this issue was opened. Please open a new issue with logs if you are still running into this.
