### ISSUE TITLE
Hidden diagnostics are not displayed in the problems panel

### ISSUE THREAD

**Issue by ExceptionGit** [dotnet/vscode-csharp#3167]
## Issue Description
Maybe after this https://github.com/OmniSharp/omnisharp-vscode/pull/2873 , the `csharp.suppressHiddenDiagnostics` option does nothing.

## Environment data
C# Extension version: 1.20.0 , v1.21.0-beta1 , v1.21.0-beta2

## Steps to reproduce
`"csharp.suppressHiddenDiagnostics": false` or `"csharp.suppressHiddenDiagnostics": true`

## Expected  behavior
Hidden diagnostics should be displayed in the problems panel.

## Actual behavior
Hidden diagnostics are not displayed in the problems panel.

**Comment by savpek** [comment]
They were modified work so that `csharp.suppressHiddenDiagnostics` controls will hidden diagnostic be hidden or hints instead. Hints are visible as small dots in editor. However they are not visible in problem panel.

![image](https://user-images.githubusercontent.com/481896/61181420-ef990480-a62e-11e9-817e-f15fa4abc991.png)

`suppressHiddenDiagnostics` was actually bit misleading, it didn't control visibility of issues but instead changed their severity in place from hidden -> information. There is mismatch between roslyn - vscode diagnostics since vscode doesn't have hidden diagnostic level at all.

As far as i know from PR/code history origin for this flag was workaround issue with unused usings where they were not visible since only analysis for them without analyzers had hidden severity. Back then there were no way to control how diagnostics behaved or what their severity was.

You can have fine grained control of issue severity and visibility with `.ruleset` files which are now supported in bot analyzers enabled and disabled.

Can you solve your use case with .rulesets? If not can you describe use case?

**Comment by ExceptionGit** [comment]
>Can you solve your use case with .rulesets?

Yes, thanks @savpek . Would be nice to change the flag description to a more detailed.

**Comment by rchande** [comment]
@savpek Is there a way to do this without using a ruleset file?

**Comment by savpek** [comment]
@rchande I don't think that can be made without rulesets at current release.

**Comment by fgimian** [comment]
I will admit that this default behaviour confused me too.  My expectation would be that such errors would appear in the Problems panel.  It would be awesome to see a setting that allowed this to be the case without editing the ruleset or .editorconfig file.

**Comment by JoeRobich** [comment]
VS Code does not display hint diagnostics in the problems panel. See https://github.com/Microsoft/vscode/issues/45436
