### ISSUE TITLE
Method references no longer contain virtual or overrides

### ISSUE THREAD

**Issue by Figbash** [dotnet/vscode-csharp#3214]
## Issue Description ##
After upgrading 1.21.0, using peek references or find all references on a virtual method no longer shows the virtual method or its overrides in the reference list, making the feature fairly useless in many situations.

## Steps to Reproduce ##
Override a method then run peek references or find all references on it.

## Expected Behavior ##
<img width="1872" alt="Screen Shot 2019-08-05 at 10 22 52 AM" src="https://user-images.githubusercontent.com/1824057/62480034-09c88d00-b76c-11e9-9cdd-56998849a917.png">

## Actual Behavior ##
<img width="1871" alt="Screen Shot 2019-08-05 at 10 20 57 AM" src="https://user-images.githubusercontent.com/1824057/62480044-0fbe6e00-b76c-11e9-8d75-a715b13153f6.png">

## Environment information ##

**VSCode version**: 1.36.1
**C# Extension**: 1.21.0

<details><summary>Mono Information</summary>
        OmniSharp using global mono :5.16.0</details>
<details><summary>Dotnet Information</summary>
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.20.0|
|mono-debug|ms-vscode|0.15.8|
|shader|slevesque|1.1.4|
|shaderlabvscodefree|amlovey|1.1.3|
|theme-batman|none|0.0.1|
|theme-bungler|none|0.0.1|
|theme-monakai-ed-2|none|0.0.1|
|theme-Monokai-Ed|none|0.0.1|
|unity-debug|Unity|2.7.2|
|vsc-material-theme|Equinusocio|29.2.0|
|vscode-multi-line-tricks|bigous|0.0.3|
|vscode-subword-navigation|ow|1.2.0|;

</details>

**Comment by coeyes** [comment]
This feature is removed since 1.20.0

see #3027 

But, I think this patch should be reverted, or maybe optional.

Because other languages in VSCode (ie. JS/TS, Python, C/C++, dart, etc.) includes definition self in Peek References/Find all references results, and code lens reference results exclude defintion. I think this was intentional, and rational. also, Visual Studio has same result.

this inconsitancy between C# and other languages is very confusing for usability.

Please, thie feature should be reverted back, or optional.

cf) even vscode-go extension revert back this feature for same reason.
    (see https://github.com/Microsoft/vscode-go/issues/562)

**Comment by JoeRobich** [comment]
Closing due to little activity. To find the implementations of `OnObjectInfo` you can use the Find All Implementations command.
