### ISSUE TITLE
Does not open Visual Studio Solution Files

### ISSUE THREAD

**Issue by bleepzter** [dotnet/vscode-csharp#3333]
**Repro Steps:**
1. Open Visual Studio Code
2. Click File -> Open File
3. Select a Visual Studio Solution file from the file system.
4. Click Open

 **What happened**
- The solution file was opened as though it is a text file.

**What should have happened:**
1. The solution should've been loaded as though it is a "workspace".
2. All files referenced by the solution should have been displayed in the explorer window.

**Note:** 
Why would you dub this a"C#" editor if you can't even support solution files?
Most developers use Visual Studio and solution files are the way to work with c# projects. If you provide a "first class" support for C# this kind of a prerequisite?!? 

**VS Code Version:**
Version: 1.38.1 (system setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

**Snapshot**
![image](https://user-images.githubusercontent.com/3333921/66507895-b2110f80-ea95-11e9-968b-4430622ab703.png)

**Comment by cartermp** [comment]
This isn't strictly something we support and will need to design an experience around, since VSCode is very different from VS, and typical VS-isms like opening a solution file don't quite fit in with how VSCode typically works. But I think there's room for a solution explorer view.

Separately, there is a selector UI where you can select a solution and it will load all of it in the editor.
