### ISSUE TITLE
Omnisharp needs faster intellisense

### ISSUE THREAD

**Issue by SamHSmith** [dotnet/vscode-csharp#3421]
## Feature Request
VSCode is supposed to be light weight and therefor faster than an ide. Why is it then that both visual studio and monodevelop trump VSCode in intellisense. As soon as project start to grow it becomes very apparent how slow intellisense is. Maybe someone could look into why this is the case?

**Comment by cartermp** [comment]
Hey @SamHSmith I definitely agree that performance could be made better. Do you have some specific actions you take where it's slower to respond than normal? Concrete performance problems can typically be resolved, whereas more general issues are not very actionable. There are likely a number of factors involved here, so narrowing things down into specific actions can make it easier to progress.

**Comment by filipw** [comment]
https://github.com/OmniSharp/omnisharp-roslyn/pull/1761 was merged

**Comment by cartermp** [comment]
@filipw unfortunately work like that, while useful, is kind of a shot in the dark. Unless there's a repro we can inspect and profile, it's impossible to say if an improvement like that has addressed the issue @SamHSmith is seeing.

**Comment by SamHSmith** [comment]
@cartermp Sorry for the slow response. I haven't used vscode or csharp in quite some time but I remember my main issue being an extreme delay between pressing ctrl + space and the app reacting.
Not an issue on small projects but as the dependency list grew and grew it became a real problem. Maybe some kind of O(n^2) situation.

**Comment by ChristopherHaws** [comment]
I am having this issue as well. In a new ASP.NET Core controller, when I type `this.` to get intellisense, the suggestions window pops up immediatly but shows `Loading` for about 8 seconds before showing results. To give you an idea of the size of my project, here is the output from [`cloc`](https://github.com/AlDanial/cloc):

```
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C#                             651          38991           5232         154483
JSON                            14              0              0          21244
TypeScript                     337           3286            204          18108
XML                              7              5              0           6670
PO File                          1            803             59           2101
Razor                           32            195             12           1391
Sass                            21            131              6            668
MSBuild script                  11             40              6            239
JavaScript                       3             20              6            177
Markdown                         2             20              0             51
SVG                              3              0              0             47
HTML                             1              4              0             33
-------------------------------------------------------------------------------
SUM:                          1083          43495           5525         205212
-------------------------------------------------------------------------------
```

**Comment by rib** [comment]
I've now got into a routine of disabling this plugin when I actually need to focus on coding because the intellisense is just _soooo_ frustratingly slow that I basically can't type at a normal speed - which feels like a fairly ridiculous thing to have to be doing.

I'd love to have the functionality but not at the expense of being able to type whenever the plugin is stuck thinking about something.

It seems like maybe one of the problems is that it isn't working fully asynchronously - being slow is one thing but _also_ synchronously blocking the user from typing seems really bad.

I saw a mention somewhere about the whole text file being sent to omnisharp each keystroke and that could be a scalability concern but right now I'm working with a text file with fewer than 500 lines of code and at times I'm seeing lagging in the order of one second per key press.

**Comment by an-dr-eas-k** [comment]
@rib you could try my manual build from HEAD with the merged PR #4310. Download here: https://drive.google.com/file/d/18hsqlEGhneRJ9w2SJQF87c5WwlrQ3IKu/view?usp=sharing

**Comment by rib** [comment]
cool, thanks, I think maybe there's also something up with the performance of vscode in general for me actually, so all the blame probably doesn't really lie with omnisharp-vscode, it's maybe just exagerated (I realise now I'm also see very slow performance at times with this addon disabled). It could just be something like memory usage somewhere that's pushing me off a huge performance cliff.

The machine I'm using has 16GB of RAM but with Unity, vscode and a browser open then it's potentially just not enough and then as soon as the machine starts heavily swapping into Windows' virtual memory on disk then I guess it's game over.

**Comment by rib** [comment]
Just to follow up with a recent discovery: after I upgraded my system to 32GB of RAM and was still finding vscode lag to be unusable I eventually found that I'm probably hitting this other vscode issue here: https://github.com/microsoft/vscode/issues/107016 - (Chromium/Electron can sometimes incorrectly enter an accessibility mode which has some severe performance problems associated with it.)

I've found I've been able to workaround this issue by using `--disable-renderer-accessibility` and so the problem (at least for me) probably isn't an Omnisharp issue at all, it's just what I was assuming since it felt a lot like the lag was from intellisense.

**Comment by seikosantana** [comment]
> I've found I've been able to workaround this issue by using --disable-renderer-accessibility

Is there any way to make this a default instead of having to type this in each time i have to start vscode?

**Comment by JoeRobich** [comment]
There have been a lot of improvements since this issue was opened. Please open a new issue with logs if you are still having trouble.
