### ISSUE TITLE
Release the "download external dependencies" code as a standalone package

### ISSUE THREAD

**Issue by felipecrs** [dotnet/vscode-csharp#3785]
This extension seems to have a strong mechanism for downloading external dependencies, how about to release this part of code as a standalone npm package for other extensions to use?

This approach can also be a solution for https://github.com/microsoft/vscode/issues/23251.

**Comment by cartermp** [comment]
The goal here is definitely fine. We want to decouple some of these dependencies from the plugin and factor them into individual plugins that this plugin will take a dependency on (e.g., .NET Core plugin, .NET Core debugger plugin, etc.)

**Comment by gregg-miskelly** [comment]
Ultimately we would like to delete our dependency downloading code in favor of: https://github.com/microsoft/vscode/issues/23251

**Comment by gregg-miskelly** [comment]
Yes, I am not saying that such code shouldn't exist anywhere in the universe, but this issue was opened as a request for this extension to pull out the dependency download code. The source code in this extension is MIT licensed, so anyone is welcome to take the code and make an NPM package themselves. But I am skeptical that it makes sense for the owners of this extension to be involved since we hope to stop using such code soon.

**Comment by JoeRobich** [comment]
Closing as we have no plans to package our package management code as a library.
