### ISSUE TITLE
Custom IProjectSystem questions

### ISSUE THREAD

**Issue by ghord** [dotnet/vscode-csharp#4226]
Hello,
First of all, I wanted to thank you for working on such brilliant tool, it's very well designed and useful for me.

I'm working on custom scripting runner which will run C# scripts with different extenion than `.csx` (mostly needed for windows file association to be able to launch said files with double click, and also custom `Globals` script object.

I've managed to get omnisharp to support Intellisense in such files by implementing custom `IProjectSystem` based on the `OmniSharp.Script` implementation (basically copy and paste of this code with different extension). This project system is loaded using `Plugins.LocationPaths` in `omnisharp.json` file and loads without issues.

Both Intellisense and debugging works brilliantly, but I'm having couple of issues and I have few questions if you dont mind:

1. When I open a file/directory with scripts of my custom extension `*.hkx`, OmniSharp server does not launch. I have set both:
```json
    "files.associations": {
        "*.hkx": "csharp"
    },
``` 
in my vscode `settings.json`

and I've also tried adding 
```
"workspaceContains:*.hkx",
"workspaceContains:**/*.hkx"
```
to `activationEvents` in `package.json` of OmniSharp with no effect. 

OmniSharp server only launches automatically if I have `csx` file in my workspace already (Adding empty .csx file to worksapce is hackish workaround but it works). Is there some other place I would need to change something?

2. Implementing custom `IProjectSystem` seems quite involved and I had to duplicate a lot of code with marginal changes. Are there any plans to make it easier by either:
    - Specifying custom script file extensions in `ScriptProjectSystem` configuration
or
    - Exposing `OmniSharp.Scripts` in nuget package and making it more extensible so that it can be inherited 

I'm willing to put the work into implementing this feature if this is something that could potentially be merged.

**Comment by filipw** [comment]
Thanks for the issue. Ideally you should really open 2 separate issues, because the C# extension for VS Code and the OmniSharp server are two separate things, versioned and released separately. The server is then used by multiple clients such as this VS Code extension, but also extensions for e.g. Emacs or VIM. You can find OmniSharp server repo here https://github.com/OmniSharp/omnisharp-roslyn

Your first question is specifically aimed at the extension while the second one (and the title of this issue) is server specific.

1. auto start of OmniSharp server is coupled to the supported file extensions for now, see e.g. here https://github.com/OmniSharp/omnisharp-vscode/blob/6608b739146123e920f410da5f29b9abfa8309eb/src/omnisharp/server.ts#L487-L491
I don't have a strong opinion whether this should be configurable or not - perhaps @JoeRobich wants to chime in?

2. There is no problem to publish `OmniSharp.Script` to Nuget - we already publish the MSBuild project system (https://www.nuget.org/packages/OmniSharp.MSBuild/) - for scripts simply no one asked for that yet 😄 
We could consider adding custom script extensions support on the server side, although I am not generally in favor of that. From what you are saying, you will need custom globals support anyway, so it will only take you a step further because we don't support loading custom host objects. So I'd be in favor of supporting these scenarios via plugin infrastructure only. If you want we can model certain things better in `OmniSharp.Script` (e.g. add virtual methods where needed or change accessibility of some stuff) to give you better experience when consuming the Nuget package

**Comment by ghord** [comment]
Thank you for finding the time to respond, and sorry for the confusion with repositories. 

1. It looks to me like autostart cannot be supported without adding a new feature to `omnisharp-vscode`. Some options include:
   - Adding configuration option to omnisharp-vscode so that it recognizes additional file extensions. Since that would be something that is only useful for vscode extension, such options placed in `settings.json` in vscode instead of `omnisharp.json`, or is there another place for editor specific settings? I'm unsure if this would be inline with extensions for other editors.
   - Different option would be to get a list of supported file extensions registered as `IProjectSystem` from OmniSharp server, since they are available is `IProjectSystem.Extensions`. It would have additional benefit of not hardcoding supported extensions in `omnisharp-vscode`. I'm not sure this is possible without launching OmniSharp server just to ask it what is supported (that is out of question I think). 
   - Another solution/workaround would be to add a command to start OmniSharp server manually (I see command to restart the server, but no command to start it if it is not already running). I could then potentially develop another vscode extension myself that simply launches this command and takes a dependency on omnisharp-vscode (`extensionDependencies` in extension manifest). Or I could leave it as it is and inform the user to start OmniSharp server manually with this command if IntelliSense is desired. It doesn't seem like too much of a bother honestly.

    Is there some option out of those three that would be worth pursuing? Should I create a new issue with a feature request or leave current issue as it is?

2. I agree this is not correct repository for the request, and I'll create and issue in `omnisharp-roslyn` about packaging `OmniSharp.Script` along with some improvements to extensibility once I identify which properties/methods would have to be virtual to allow extensibility.

    As for the globals support, I wanted to use it to expose some static methods to the script without the need for the user to import them (basically preconfigured static usings, which are not supported by `.rsp` files from what I understand). I think that could be also achieved by other means, like adding additional script files to OmniSharp workspace at server runtime. I don't think lack of support for custom Globals is a problem for me.

**Comment by JoeRobich** [comment]
Closing as support for custom file extensions isn't planned.
