### ISSUE TITLE
Accepting the decompiler agreement permanently

### ISSUE THREAD

**Issue by ssoher** [dotnet/vscode-csharp#4296]
Issue Type: <b>Bug</b>

If the decompilation support is enabled, the warning message associated with it is shown every time Visual Studio Code is opened, even with non C# folders. Isn't it supposed to be shown once, only when decompilation feature is enabled? Maybe a "Don't show again" toggle can be added.

![image](https://user-images.githubusercontent.com/4283979/102156693-1ea04f00-3e8f-11eb-866f-1b7195c6d17b.png)

Extension version: 1.23.7
VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.18362

**Comment by SentientCoffee** [comment]
Bumping this because it is starting to get very annoying to have to deal with this popup every time I want to use VS Code. I can understand if this gets enabled when I open a C# project, but having the popup happen while I'm trying to just open a fresh instance of VS Code is not really desirable in my opinion. Also, I turned on decompilation support manually myself, so ideally this should only ever pop up ONCE, and I should be able to say "Don't show this to me again."

**Comment by T3kla** [comment]
I'm deactivating the functionality just because of the continuous warnings. What a shame.

**Comment by mikadumont** [comment]
This is no longer applicable in the latest version of the C# extension.
