### ISSUE TITLE
Error at start up of omnisharp: mtoken: 0x0a000006 due to: Cannot resolve dependency to assembly because it has not been preloaded

### ISSUE THREAD

**Issue by paillave** [dotnet/vscode-csharp#4331]
System: ubuntu 20.04

1. Open Visual Studio Code v1.52.1
2. Open my (very big) C# project

Omnisharp mentions me the following errors

Actually, one project of my solution uses these assemblies (`microsoft.codeanalysis.*****`). But, something interesting: if I put appart the project that references assemblies that seem to be the source of the problem and open it alone in VSCode, I don't get the problem.

Information: my solution is **VERY** big.

```
Starting OmniSharp server at 1/5/2021, 11:31:21 AM
    Target: /home/stephane/Documents/Sources/PMS/src/FundProcess.Pms.sln

OmniSharp server started.
    Path: /home/stephane/.vscode/extensions/ms-dotnettools.csharp-1.23.8/.omnisharp/1.37.5/run
    PID: 9520

Can't find custom attr constructor image: /home/stephane/.nuget/packages/microsoft.codeanalysis.csharp.features/3.8.0/lib/netcoreapp3.1/Microsoft.CodeAnalysis.CSharp.Features.dll mtoken: 0x0a000006 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
Can't find custom attr constructor image: /home/stephane/.nuget/packages/microsoft.codeanalysis.csharp.workspaces/3.8.0/lib/netcoreapp3.1/Microsoft.CodeAnalysis.CSharp.Workspaces.dll mtoken: 0x0a000006 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
Can't find custom attr constructor image: /home/stephane/.nuget/packages/microsoft.codeanalysis.features/3.8.0/lib/netcoreapp3.1/Microsoft.CodeAnalysis.Features.dll mtoken: 0x0a000006 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
Can't find custom attr constructor image: /home/stephane/.nuget/packages/microsoft.codeanalysis.csharp.features/3.8.0/lib/netcoreapp3.1/Microsoft.CodeAnalysis.CSharp.Features.dll mtoken: 0x0a000006 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
Can't find custom attr constructor image: /home/stephane/.nuget/packages/microsoft.codeanalysis.csharp.workspaces/3.8.0/lib/netcoreapp3.1/Microsoft.CodeAnalysis.CSharp.Workspaces.dll mtoken: 0x0a000006 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
Can't find custom attr constructor image: /home/stephane/.nuget/packages/microsoft.codeanalysis.features/3.8.0/lib/netcoreapp3.1/Microsoft.CodeAnalysis.Features.dll mtoken: 0x0a000006 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
```

**Comment by TheBoneJarmer** [comment]
I'm having the same issue. Omnisharp stops functioning more often. I noticed I am spending lots of time trying to get intellisense up and running again. Restarting omnisharp sometimes helps but not always.

**Comment by ppossanzini** [comment]
I have exactly the same issue.. have you fond a solution for this ?

**Comment by TheBoneJarmer** [comment]
> I have exactly the same issue.. have you fond a solution for this ?

I stopped using VS Code and started using Rider. Of course that doesn't solve this specific problem but I simply can't wait for the developers of OmniSharp to come up with a fix. I have deadlines too to catch..

**Comment by Mr-MooMoo** [comment]
Same problem here... Ubuntu 20.04 and Arch Linux (Yes, I know it's not supported ..)

**Comment by alanondra** [comment]
Running into this problem myself. This basically renders VS Code useless for C# projects.

**Comment by ppossanzini** [comment]
I've found a solution for this problem: 
the problem is due to a missing dlls from current .net version.. but same dlls are present in the previous version. 
The problem is only on linux distro.. on dotnet 5.

My solution is: 

- install previous version of SDK for example 3.1.113
- find installation folder /usr/lib64/dotnet/sdk/3.1.113 and go to subdir /usr/lib64/dotnet/sdk/3.1.113/Sdks/Microsoft.NET.Sdk.Razor/tasks/net472
- copy alll the dlls in this folder to the .net missing folder /usr/lib64/dotnet/sdk/5.0.104/Sdks/Microsoft.NET.Sdk.Razor/tasks/net46
![image](https://user-images.githubusercontent.com/1579329/115428002-40755e00-a202-11eb-9815-1fa460542292.png)

this fixed the problem for me. If you need i can provide missing dlls from my pc

**Comment by anton-rlgx** [comment]
Having same issue, but assemblies causing it are my own, from referenced F# projects. So I can't just drop those away to fix the problem. I suspect that due to this issue my C# files don't recognize namespaces from referenced F# projects, which is extremely annoying as VS Code becomes unusable. Rider behaves correctly with the same solution. 

Bottom line is: it's 2021 and dotnet 6 upcoming, yet I can't smoothly develop on Mac (no idea if Windows users are luckier) 🤦‍♂️.  I just don't have any simple and efficient tool to work all day long without stress (and time losses). VS Code is not working. Rider is overkill for me (I just don't need all those fancy features! and BTW it eats all the RAM. I have it and use occasionally when get tired of VS Code crashing, but that can't be a solution long-term). Visual Studio Mac is the last resort, yet it seems to be a poor trade-off so far. 

I feel really desperate seeing this issue with no real reaction/solution for months. As of today VS Code (at least on Mac) is NOT for dotnet development (whatever ridiculous it may sound). It's a very cool IDE, but for something else other than dotnet. So either switch to other OS/IDE, or just develop in typescript/haskell etc LOL.

**Comment by JoeRobich** [comment]
There have been lots of improvements since this issue was opened. Please open a new issue with logs if you are still running into this.
