### ISSUE TITLE
A lot of intellisense issues

### ISSUE THREAD

**Issue by MathiasSvDK** [dotnet/vscode-csharp#4455]
Hi.
Am i the only one experiencing a lot of intellisense issues and false errors?

I am using a Apple M1 - i have tried my code on a Windows machine and there are no errors.

VS Code version:
Latest
C# Extension version:
Latest

**Comment by noslavde** [comment]
I haven't had any luck finding any mention of this, but I too am having intermittent issues of false errors. I have never looked here though.

Case:  I'm using VS Code with Unity. 
Platform: Windows 10
Versions: All latest.

Details and Commentary:
This is an old issue for me and has occurred over many versions for well beyond a year's time. The only thing I've found to help is restart, recompile, reboot. I don't know what goes on behind the scenes for this to occur, but something about resetting some of these things _eventually_ works. 

Basically what happens is one or more scripts will throw dozens to hundreds of errors; saying invalid something or other, namespace doesn't exist, etc. Think of an error, it's there. But the thing that I find odd, is that in those scripts with errors exists things that in other scripts with the same do not give errors. It also throws syntax highlighting way out of whack. 

Yet, the code compiles just fine. Bizarre, disruptive, and confusing at times. Occasionally it'll trigger and I'm unsure whether there really is an error or if it's bugging out.

My best guess for what happens in my case is that Unity won't compile until all errors are resolved, and it might be jacking up the connection between it and VS Code/Omnisharp. I wouldn't be surprised if it's more Unity's fault though, since they've only recently started bridging with VS Code. Anyways, hope this is helpful.

**Comment by Lobosque** [comment]
I have issues like this all the time, and also sometimes omnisharp is so slow that it takes 15 minutes to have all files parsed.

**Comment by JoeRobich** [comment]
@imflitch Can you please sahre the OmniSharp log from the Output pane?

**Comment by tiagoalberto** [comment]
I'm trying to use a M1 Macbook but there is no intellisense with Razor. It's in the release pipeline fixing this?

**Comment by JoeRobich** [comment]
Closing due to lack of response.
