### ISSUE TITLE
Suggestions not showing

### ISSUE THREAD

**Issue by Harras420** [dotnet/vscode-csharp#4650]
When I first downloaded VS Code and put the C# extension on, everything worked fine. All the suggestions showed while I was typing. But all of a sudden nothing is working anymore. I have closed and opened VS Code, I have uninstalled and reinstalled VS Code, I have uninstalled and reinstalled the C# extension, but nothing seemed to work. Below is a picture of no suggestions showing for the word "transform".

![Transform](https://user-images.githubusercontent.com/77969473/125308555-4a09f000-e331-11eb-9dc3-bb3cb5fc188a.PNG)

The only suggestions that do show are words I already typed earlier in the class. Below is a picture that shows the only suggestions I get.

![Suggestions](https://user-images.githubusercontent.com/77969473/125308567-4d9d7700-e331-11eb-8b0b-0b42639d2488.PNG)

So for someone like me that doesn't fully know the C# language. It is super hard to code what I want to code. Even if I did know the C# language, it would take forever to code anything. Does anyone know what happened or what I can do? I also receive these errors when opening VS Code:

![Error1](https://user-images.githubusercontent.com/77969473/125310479-e84a8580-e332-11eb-907c-64e575bfa078.PNG)

I have the latest version of .NETFramework. Do I need to go back to the older version or is it still supposed to work with the newer version of .NETFramework?

![Error2](https://user-images.githubusercontent.com/77969473/125310498-ebde0c80-e332-11eb-957c-813c1a2ce887.PNG)

I think it all went south when I started using Unity. I think it happened when I opened a C# Script from within Unity, but I don't know for certain.

Any help would be greatly appreciated.

**Comment by vyshnavks8** [comment]
The simple solution for this problem is to downgrade c# extension in vscode. You can do this by pressing  arrow on uninstall button and choose to install another version. 

![csharp](https://user-images.githubusercontent.com/37574513/125516609-94c75a4f-4f05-429c-adc7-499e7bed23fc.png)

I think this solution might help you for the time being.
Previous V1.23.12 worked perfectly for me. I also had the issue of intellisense suggestion problem after updating to the V1.23.13
I think the developer will look into this Issue.

Mono Version : Mono JIT compiler version 6.12.0.122
Dotnet SDK Version : 5.0.302
Dontnet runtime Version : 5.0.8

**Comment by JoeRobich** [comment]
@Harras420 Unity requires that the .NET 4.7.1 target pack be installed.  You can install the pack from https://www.microsoft.com/en-us/download/details.aspx?id=56119

**Comment by JoeRobich** [comment]
@vyshnavks8 If you are running into problems with the latest release, could you please open an issue so that we can investigate. Thanks!

**Comment by JoeRobich** [comment]
Closing as answered.
