### ISSUE TITLE
The extension can't find the .NET path WINDOWS

### ISSUE THREAD

**Issue by RUGMJ** [dotnet/vscode-csharp#4840]
## Issue Description ##

I have installed .NET and have checked in cmd that it is in the path where.exe dotnet responds with the path of dotnet

```
>where.exe dotnet
C:\Program Files (x86)\dotnet\dotnet.exe
C:\Program Files\dotnet\dotnet.exe

```
I have rebooted my machine and have restarted vscode even tried opening vscode form the command line.

## Steps to Reproduce ##

Install .NET and try to use the extension

## Expected Behavior ##

The extension finds .NET

## Actual Behavior ##

It dosnt...

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.61.2
**C# Extension**: 1.23.16

<details><summary>Dotnet Information</summary>
A valid dotnet installation could not be found.</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|Arduino|moozzyk|0.0.4|
|arduino-snippets|ronaldosena|1.0.2|
|auto-close-tag|formulahendry|0.5.12|
|auto-rename-tag|formulahendry|0.1.9|
|bash-beautify|shakram02|0.1.1|
|bracket-pair-colorizer-2|CoenraadS|0.2.1|
|cdn-list|AryanMann|1.0.0|
|code-beautifier|michelemelluso|2.3.3|
|cpp-extentions-pack|boundarystudio|0.3.0|
|cpptools|ms-vscode|1.7.1|
|csharp|ms-dotnettools|1.23.16|
|discord-vscode|icrawl|5.7.0|
|google-fonts|lior-chamla|0.0.1|
|html-css-class-completion|Zignd|1.20.0|
|java|redhat|1.0.0|
|javascript-ejs-support|DigitalBrainstem|1.3.1|
|linux-themes|SolarLiner|1.0.1|
|live-sass|ritwickdey|3.0.0|
|LiveServer|ritwickdey|5.6.1|
|markdown-checkbox|bierner|0.3.2|
|markdown-preview-enhanced|shd101wyy|0.6.1|
|material-icon-theme|PKief|4.10.0|
|minifyall|josee9988|2.10.0|
|npm|idered|0.5.2|
|npm-intellisense|christian-kohler|1.4.0|
|path-intellisense|christian-kohler|2.4.0|
|prettier-vscode|esbenp|9.0.0|
|project-manager|alefragnani|12.4.0|
|sass-indented|syler|1.8.18|
|spwn-language-support|Spu7Nix|0.0.5|
|statusbar-commands|anweber|2.1.0|
|synthwave-vscode|RobbOwen|0.1.10|
|tabnine-vscode|TabNine|3.4.33|
|TabOut|albert|0.2.1|
|template-string-converter|meganrogge|0.5.3|
|unity-code-snippets|kleber-swf|1.3.0|
|unity-debug|Unity|3.0.2|
|unity-toolbox|pixl|1.0.6|
|unity-tools|Tobiah|1.2.12|
|vs-code-node-require|tgreen7|1.10.2|
|vs-color-picker|lihui|1.0.0|
|vscode-arduino|vsciot-vscode|0.4.6|
|vscode-autohotkey-plus|cweijan|2.6.2|
|vscode-computercraft|JackMacWindows|1.1.0|
|vscode-express-snippets|ExpressSnippets|1.1.1|
|vscode-html-css|ecmel|1.10.2|
|vscode-http-client|mkloubert|0.34.0|
|vscode-import-cost|wix|2.15.0|
|vscode-java-debug|vscjava|0.36.0|
|vscode-java-dependency|vscjava|0.18.8|
|vscode-java-pack|vscjava|0.18.6|
|vscode-java-test|vscjava|0.32.0|
|vscode-maven|vscjava|0.34.0|
|vscode-npm-script|eg2|0.3.23|
|vscode-profile-switcher|aaronpowell|0.3.3|
|vscode-scss|mrmlnc|0.10.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.14|
|vsliveshare|ms-vsliveshare|1.0.5043|;

</details>

**Comment by dwtaber** [comment]
> @RUGMJ7443 In 64-bit environments the .NET SDK will fail to be discovered if the 32-bit dotnet path come before the 64-bit dotnet path in the Environment PATH variable.

Putting the 64-bit version ahead of the 32-bit version in PATH did resolve the issue for me.  It would be nice if [this troubleshooting page](https://github.com/OmniSharp/omnisharp-vscode/wiki/Troubleshooting:-'The-.NET-Core-SDK-cannot-be-located.'-errors) included that information.  I don't see a way to PR or otherwise update the page myself; can you or another Omnisharp member add it?

**Comment by RUGMJ7443** [comment]
I have removed the 32bit path from my path though....

**Comment by dwtaber** [comment]
Sorry, @RUGMJ7443, I was quoting @JoeRobich and inadvertently included the part where they tagged you.  I've edited the post for clarity.

**Comment by JoeRobich** [comment]
@dwtaber Thanks for the suggestion. Added a note to the troubleshooting wiki. Going to close this issue out.

**Comment by RUGMJ7443** [comment]
> 
> 
> @dwtaber Thanks for the suggestion. Added a note to the troubleshooting wiki. Going to close this issue out.

But my issue still isnt fixed....

**Comment by JoeRobich** [comment]
@RUGMJ7443 Can you please share the OmniSharp log and the C# log from the Output pane? As well as the output of `dotnet --info`.

**Comment by RUGMJ7443** [comment]
Will do tonight.

**Comment by 28amit** [comment]
> > In 64-bit environments the .NET SDK will fail to be discovered if the 32-bit dotnet path come before the 64-bit dotnet path in the Environment PATH variable.
> 
> Putting the 64-bit version ahead of the 32-bit version in PATH did resolve the issue for me. It would be nice if [this troubleshooting page](https://github.com/OmniSharp/omnisharp-vscode/wiki/Troubleshooting:-'The-.NET-Core-SDK-cannot-be-located.'-errors) included that information. I don't see a way to PR or otherwise update the page myself; can you or another Omnisharp member add it?

How can I put 64-bit version ahead of 32-bit version?

**Comment by thomazmoura** [comment]
I know this is an old issue but it seems to be one that keeps coming back so I thought it might be worth to share my case and the solution.

I've also been having problems for a while now on Windows and none of those solutions had any effect on it. it kept giving the error "A valid dotnet installation could not be found" even though I clearly had it installed and could "reach" it from both CMD, PowerShell and pwsh. The only thing that fixed it to me was change the SHELL environment variable (which I had previously changed to run pwsh instead of CMD so it would be default shell open on WezTerm) back to CMD.

I suspect that somewhere on the process of discovering the dotnet version it runs something like "where dotnet" instead of "where.exe dotnet" and this works fine on CMD but fails on PowerShell (because where is an alias to Where-Object).

Anyway, might be worthy to investigate that or put the workaround of keeping CMD on $env:SHELL variable on the troubleshooting page.

**Comment by JoeRobich** [comment]
A lot has changed with O# sdk resolution since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues****
