### ISSUE TITLE
the auto gen debug config show set the file extension to .exe instead of .dll when the project is WPF/WINFORM

### ISSUE THREAD

**Issue by heartacker** [dotnet/vscode-csharp#4925]
`dotnet --info` output:
VS Code version: all
C# Extension version: all

## Steps to reproduce
1. open a folder with wpf csproj file

## Expected  behavior
create a debug and task config and the  debug target should be end with `.exe`

## Actual behavior
end with `.dll`

**Comment by gregg-miskelly** [comment]
Is your WFP project running on .NET Core? If so, this is "by design" -- your user code winds up in \<ProjectName\>.dll. The build system will, depending on version, OS and flags, also drop a '\<ProjectName\>.exe' stub that is NOT your code but is rather a little boot strap exe from the .NET SDK/Runtime. This extension always points at the .dll because that always works instead of trying to figure out if your project is configured to drop the .exe.

**Comment by JoeRobich** [comment]
Closing as answered.
