### ISSUE TITLE
 'OmniSharp: Select Project' resulted in an error

### ISSUE THREAD

**Issue by trungnguyen10** [dotnet/vscode-csharp#4942]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by PsychoNineSix** [comment]
I was told in a previous issue that this is fixed in a prerelease:

https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.23.18-beta2

**Comment by TomasEkeli** [comment]
how do i use the pre-release? it doesn't seem to be published in a way that i can easily select that version

**Comment by gregg-miskelly** [comment]
https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases

**Comment by jannickj** [comment]
can someone on the omnisharp team please release the fix, or at least rollback breaking changes... ?, my omnisharp has been broken for days now :(

**Comment by JoeRobich** [comment]
> team please release the fix, or at least rollback breaking changes...

@jannickj Sorry, the changes in the new VS Code release conflicted with our existing behavior. Please try installing one of our prerelease builds (https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.24.0-beta1) that include a fix. At this point we won't be able to do a proper release until after the winter holidays.

**Comment by jannickj** [comment]
yeah my bad I forgot to update my comment I thought it was a broken release on omnisharp, but it was vscode that made the breaking change.

**Comment by tarus622** [comment]
When I uninstall the extension C# Dev Kit, the problem is fixed. I think that has a conflict with that extension and Omnisharp.
![omnisharp_1](https://github.com/dotnet/vscode-csharp/assets/94433435/9e0ac025-cac1-4f2a-b369-7701044a7896)
![omnisharp_2](https://github.com/dotnet/vscode-csharp/assets/94433435/775724b8-08dc-44f5-9686-a3ce9ec7e447)
![omnisharp_3](https://github.com/dotnet/vscode-csharp/assets/94433435/67218d45-9464-4b37-b114-936a0e868544)

**Comment by JoeRobich** [comment]
Closing as original issue is resolved.
