### ISSUE TITLE
Cannot generate launch.json and tasks.json on linux@arm64 automatically

### ISSUE THREAD

**Issue by Solar-Matrix-Core** [dotnet/vscode-csharp#4978]
## Environment data
`dotnet --info` output: 6.0.101
VS Code version: 1.63.2
C# Extension version: 1.23.16
OS Environment: Kylin V10 (based on Debian 10) @ ARM64

## OmniSharp log
No log

## Steps to reproduce
Running vscode command `.NET: Generate Assets for Build and Debug`

## Expected behavior
`build.json` and `tasks.json` created and found in `.vscode` dir

## Actual behavior
Nothing happened

**Comment by gregg-miskelly** [comment]
This is currently expected -- launch.json generation requires a language service, and by default, there is no linux-arm64 language service. If you haven't already done so, you can enable the experimental new .NET 6-based language service. See [here](https://github.com/OmniSharp/omnisharp-vscode/blob/173fa7934143bcce3a9e47cd378f771e0369c292/README.md#using-net-6-builds-of-omnisharp) for more information. If you are already doing this, please provide an OmniSharp log so that someone one the language service team can try to help.

**Comment by JoeRobich** [comment]
Closing as answered
