### ISSUE TITLE
C# analysis does not detect new files or DLL reference changes

### ISSUE THREAD

**Issue by GSPP** [dotnet/vscode-csharp#4983]
Issue Type: <b>Bug</b>

1. Add a new file or change a DLL that your project is referencing.
2. Observe that nothing in that new file or in the reference is being detected (e.g. errors appearing that a type was not found, but the project compiles fine in VS)

This reproduces in multiple solutions for me. I wonder why nobody has reported this before, so I wonder if my system might have something specific causing this. But I'm not sure what that could be. These solutions are rather simple in their structure.

I'm also not sure if this is a C# plugin but or a VSCode bug.

Extension version: 1.23.17
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by ThePickleJuiceMan** [comment]
I am also having this issue. When I need to rebuild one of my project's references, I lose the ability to build that project. The referenced project builds fine, but I cannot use it as a reference in my current project.

error CS0246: The type or namespace name 'AsmResolve' could not be found (are you missing a using directive or an assembly reference?)

The reference is in the correct path and rebuilt. I've even gone as far as copying the referenced .dll(s) to the same directory as my .csproj, updating the HintPath, but still cannot build. 

Restarting VS Code does not fix the issue. Reinstalling extensions does not fix this issue. I was getting omnisharp logs before troubleshooting. Something along these lines:

"Can't find custom attr constructor image: /Users/my_name/Processing/Repo/AsmResolve.dll mtoken: 0x0a000001 due to: Cannot resolve dependency to assembly because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event."

Extension Version: 1.23.17
VS Code Version: 1.63.2  899d46d82c4c95423fb7e10e68eba52050e30ba3 x64 
OS: Ubuntu 20.04.3 LTS

**Comment by GSPP** [comment]
I have now had a streak of situations where changes were detected successfully. It doesn't seem to be deterministic.

**Comment by middiu** [comment]
Same problem for me.

2 Projects, Project A reference Project B.

Both Projects are open and loaded in two distinct VSCode windows, both are building and running fine.

If a change is made on Project B, Project A doesn't see the change. The only workaround for me is to restart OmniSharp from VSCode command line.

I guess this is a bug.

Cheers

**Comment by JoeRobich** [comment]
A lot has changed with O# code analysis since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues
