### ISSUE TITLE
I get a popup to install latest Mono (have previously installed it)

### ISSUE THREAD

**Issue by andymads** [dotnet/vscode-csharp#5642]
Type: <b>Bug</b>

When opening a project I get a popup stating the following, however I have followed the link and already installed the latest version (6.12.0 stable channel), and restarted.

OmniSharp requires a complete install of Mono (including MSBuild) to provide language services when `omnisharp.useModernNet` is disabled in Settings. Please install the latest Mono and restart.

Extension version: 1.25.4
VS Code version: Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T09:55:48.214Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|24.00GB (1.20GB free)|
|Process Argv|/Users/andymaddison/Mads/Unity/FirebaseRemoteConfig/FirebaseRemoteConfig.UnityProject --crash-reporter-id cecc6bc9-800f-41d9-9745-3829d8480fa4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyonecf:30548226
vscccc:30610679
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
defaultazurewalk:30687958
pythonms35:30701012

```

</details>

**Comment by zsilverzweig** [comment]
Same issue.

**Comment by ericdrobinson** [comment]
I, too, am seeing this.

I have `mono` (version 6.12.0.182) installed here:

```
/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono
```

Whenever I open a Unity project that has `useModernNet` disabled, I get the error mentioned in the top post and I see an error notification in the bottom right with this message:

> The .NET Core SDK cannot be located: A valid dotnet installation could not be found. .NET Core debugging will not be enabled. Make sure the .NET Core SDK is installed and is on the path.

I also have `dotnet` (version 7.0.100) installed here:

```
/usr/local/share/dotnet/dotnet
```

To be clear, both `mono` and `dotnet` are available by default in VS Code's terminal without full path. Is the PATH used by the extension somehow different from that used by VS Code's built-in terminal?

**Comment by ericdrobinson** [comment]
I did a bit of version bisecting and the message started appearing with Omnisharp v1.25.2 (v1.25.1 still works*).

_* I should point out that I still see the same "The .NET Core SDK cannot be located..." error on v1.25.1. It's just that features like "Go to Symbol" actually work._

**Comment by ericdrobinson** [comment]
Also, #5518 appears to be related to this.

**Comment by Rica02** [comment]
I got this same issue with Omnisharp 1.25.7 (Mono 6.12.0, VSCode 1.78.2 and Monterey 12.6). Tried downgrading Omnisharp to 1.25.1 but I still got the popup. But it disappears after downgrading to **1.25.0**.

**Comment by JoonatanKuuhubb** [comment]
Setting mono path in vscode settings `omnisharp.monoPath` fixed this for me

**Comment by LCWilliams** [comment]
Just echoing this extremely infuriating issue.

Doesn't matter what paths I set, this plugin just ignores them all and proclaims it can't find anything!

1.25.**0** works.

Unity 2022 LTS.
Mono 6.8.0.105
dotnet 7.0.105
Linux Mint 21 (Jammy)

**Comment by ericdrobinson** [comment]
Update regarding [my previous comment](https://github.com/dotnet/vscode-csharp/issues/5642#issuecomment-1552112895): My experiences with 1.25.**1** are hit-or-miss. 1.25.**0** appears to work without the error and pretty well starts up as expected.

@JoeRobich As someone who has been experiencing this as well (macOS 13.4 on Apple Silicon, VS Code 1.79.2, OmniSharp 1.25.1 and up causing issues...), I figured I'd give your `msbuild -ver` thing a shot and provide my own info. I ran that command within VS Code's Terminal and received this:

```
Microsoft (R) Build Engine version 16.10.1 for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

16.10.1.31401% 
```

What's **_super weird_** is that after running that command, changing the installed version of the extension _away_ from 1.25.**1** (which had worked for me for a bit), suddenly enabled the extension to work as expected. I've tried a few versions in the 1.25.x range and now _only_ 1.25.1 fails to work? Importantly, 1.25.9 (latest at time of writing) _does_ seem to work as expected.

During these tests I updated from VS Code 1.79.1 to 1.79.2, which restarted VS Code. I mention this because perhaps there was something in VS Code itself that fixed things? Or perhaps a local extension installer cache that had been misbehaving in some way? I'm depositing these thoughts here as variables that may have affected my "success".

In short, I have the version of `msbuild` referenced above. My OmniSharp install started to work after checking the `msbuild` version. Things now seem to be okay.

This may also be noise, but I should point out that the Mono `msbuild` is installed as a tiny shell script with the following contents:

```sh
#!/bin/sh
MONO_GC_PARAMS="nursery-size=64m,$MONO_GC_PARAMS" exec /Library/Frameworks/Mono.framework/Versions/6.12.0/bin/mono --assembly-loader=strict $MONO_OPTIONS /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/15.0/bin/MSBuild.dll "$@"
```

Given that it started working _after_ I ran the `msbuild -ver` command [within VS Code's Terminal], I wonder if there's something about how the extension executes `msbuild` that might be failing until it's manually run at least once(??). I'm super unclear as to how something like that would even work, but when grabbing at straws...

**Comment by JoeRobich** [comment]
@ericdrobinson That is weird indeed! As for 1.25.1, [the release notes for 1.25.2](https://github.com/dotnet/vscode-csharp/releases/tag/v1.25.2) indicate there was a bug with the mono check in that version.

**Comment by LCWilliams** [comment]
> @LCWilliams Using the C# extension with OmniSharp for Full Framework projects requires MSBuild to be installed as well as Mono. What version of MSBuild is installed? Try running `msbuild -ver`

Yes, I'm aware after having that same unhelpful error spammed into my face for several hours.

I *eventually* got it working after spam installing both 6 & 7: dotnet#, dotnet-sdk-#, dotnet-runtime-#, and mono using the non-default repository.

**Comment by JoeRobich** [comment]
Please open a new issue with logs if you are still running into this.
