### ISSUE TITLE
[O# Parity] Dedupe build and live diagnostics

### ISSUE THREAD

**Issue by dibarbet** [dotnet/vscode-csharp#5728]
When you run a build, problems will be added to the problem window.  However once the error is fixed, the errors won't disappear until a new build is run.  We should remove these build errors when the next live diagnostics request.

Roughly how this might work in vscode
```
The recommended way on how to implement something like this in VS Code is the following:

extension one provides extension API to set sort of filter or problems piping
extension two plugs in such a filter into extension one.
In the concrete setup the implementation would be as follows:

devkit extension uses custom tasks and provides such an extension API
Roslyn extension uses the API of devkit to filter the problems or alternatively even deliver them to VS Code on behalf of the devkit extension. The Roslyn extension could also use a custom middleware to filter the problems provided by the Roslyn server or uses custom message to tell the server to not generate them at all.
```

**Comment by arkalyanms** [comment]
Moving to Becca since this in the LSP layer. This will be a GA blocker.

**Comment by beccamc** [comment]
The problem here is that DevKit extension reports the msbuild problems, and C# extension reports the Roslyn problems. VS Code doesn't allow the Roslyn extension to overwrite results from the DevKit extension. 

The DevKit extension uses the mscompile problem matcher to report problems to VS Code. There isn't a way for us to tap into the results of this problem matcher. This will require us to write a custom task via[ VS Code's API](https://github.com/microsoft/vscode/blob/5150ef0ce77ef5516e55af4b8272f25907b55953/src/vscode-dts/vscode.d.ts#L7739) for MSBuild that exposes the problem matcher

**Comment by mavasani** [comment]
Discussed this will @beccamc offline and we believe the following work is required here:

1. Rosyln LSP server: Expose an API that either exposes all build-only diagnostic IDs OR given a diagnostic ID, answers whether the diagnostic ID is build-only or not. The exact API shape and implementation would depend on the client requirements, with performance considerations in mind.

2. C# Devkit extension:
   1. Write a custom task/problem matcher to intercept build diagnostics, instead of using VSCode's `msCompile` problem matcher.
   2. Call into a to-be-added API into C# extension (see 3i. below) and pass all the build reported diagnostics to it.

3. C# extension:
   1. Expose a new API for C# devkit extension to call into with build reported diagnostics.
   2. Bucketize these diagnostics into build-only and rest using the new API added in the Roslyn LSP server in 1. above.
   3. Report the build-only diagnostics to VSCode using a new build-only diagnostic source OR identifier or some such. Prior to doing this, if this wasn't the first build in the current session, we should probably call into VSCode to clear out prior reported build-only diagnostics from this source.
   4. Drop all the cached live diagnostics till then, and also call into VSCode to clear out all the reported live diagnostics for all documents/projects
   5. Group the rest of the diagnostics from ii. above by document and project, and report these as live diagnostics to VSCode

Hopefully, above design should be doable to address this issue.

I did have one question for @dibarbet @beccamc - is it possible to implement the custom task/problem matcher mentioned in 2. above in the C# extension itself? If so, we can move bulk of all the work into the C# extension, and just need to expose a simple "build command invoked" eventing API from it. C# devkit extension would invoke this API with the given project or solution name/node and let the C# extension do everything required.

**Comment by beccamc** [comment]
This is great, thanks @mavasani! From my understanding, the custom task/problem matcher will need to be in the C# Devkit extension. However, moving it to the C# extension is a great idea and I will look into it. David please chime in if you have any other info.

**Comment by beccamc** [comment]
Implemented a custom task in Devkit that parses the build results into a format that can be easily turned into Diagnostic objects (see Devkit dev/beccam/dedupeDiagnostics). These results need to be passed to C# via brokered service. Then bucketized via the new [getBuildIdsOnly](https://github.com/dotnet/vscode-csharp/blob/42022154a5f2b618ae85871262a7b8a02acfa42b/src/lsptoolshost/roslynLanguageServer.ts#L806) api and added into a new diagnostic collection.

**Comment by beccamc** [comment]
This item requires updates to multiple components. It is in progress. 

- [ ] Update BuildOnlyDiagnosticsIds Roslyn API - https://github.com/dotnet/roslyn/pull/69475
- [ ] Add customer problem matcher to C# DevKit to process build results
- [ ] Create brokered service to send build results to C# extension 
- [ ] Dedupe live and build diagnostics in C# extension
