### ISSUE TITLE
IntelliSense/auto complete deletes text after cursor

### ISSUE THREAD

**Issue by dubiousconst282** [dotnet/vscode-csharp#5777]
## Expected  behavior
IntelliSense should append text before the cursor without erasing the rest.

https://github.com/dotnet/vscode-csharp/assets/87553666/48e64882-0d31-4efe-9502-4906ce32132b

## Actual behavior
When selecting an IntelliSense suggestion with tab, text after the cursor position will be erased.

https://github.com/dotnet/vscode-csharp/assets/87553666/5b0a98e0-a9ac-4d2b-89ce-ce30300132bf

## Additional context
I've checked older releases and they all seem to present this problem, however it may be due to external factors (latest VSCode update) since I haven't noticed it before.

There are also cases where no completion will be added: `override F|` - the popup will show but pressing tab/enter will do nothing.

## Environment data
<details>

```
Version: 1.79.0 (user setup)
Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
Date: 2023-06-07T14:26:35.552Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

Name: C#
Id: ms-dotnettools.csharp
Description: Base language support for C#
Version: 2.0.206
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp
```
</details>

**Comment by ivanpfeff-dev** [comment]
Also getting this and tried changing editor.suggest.insertMode but it didn't have an effect.
I have also not noticed this until yesterday morning and I use vscode C# every day for years.
Feature bisect told me the error was in the C# extension.

**Comment by avargaskun** [comment]
I was also hitting this issue with VSCode from May (1.79) and it is gone after downgrading to April (1.78)

Fwiw, it looks like the issue was reported and closed: https://github.com/microsoft/vscode/issues/183746

**Comment by dibarbet** [comment]
FYI @genlu , seems to be more evidence of a change in vscode causing this (and missing override completion).

**Comment by all-iver** [comment]
I'm also seeing some new behavior where autocomplete deletes text, from other comments it sounds like it might not be this extension's fault but since this issue is still open maybe it makes sense to document them here?

Here, I'm typing "grid", and then when I type a period it auto-deletes the following text.  I'm not pressing tab or anything, just a period.

[Example 1](https://github.com/dotnet/vscode-csharp/assets/991572/962f154c-6ac3-464b-8e26-1e852f9f8924)

And here, I type "var", and then when I add a space, the text "grid" is deleted (I want to type "var cell = ").

[Example 2](https://github.com/dotnet/vscode-csharp/assets/991572/51974d9d-6e9d-49c8-a4e7-56b6e5ac89df)

In both cases, previously I'm pretty sure it would just bring up completion suggestions but would not auto-delete any text.  I started noticing this a few days ago...version is 1.79.0.

**Comment by richlander** [comment]
+1 ... I have the same issue.

**Comment by YorVeX** [comment]
Also suffering from this, it's a new issue introduced in v1.79 I would say, didn't have this with the previous version.

**Comment by genlu** [comment]
Note the issue with override completion is a [different issue](https://github.com/microsoft/vscode/issues/184924) therefore not addressed by https://github.com/dotnet/roslyn/pull/68624

**Comment by Roman-Solo** [comment]
I have the same issue, but I was able to solve it by downgrading the other extension, ".NET Extension Pack" from 1.0.12 to 1.0.11.
