### ISSUE TITLE
C# DevKit won't start on my project (hostfxr.dll issue)

### ISSUE THREAD

**Issue by erikrenaud** [dotnet/vscode-csharp#5815]
VS Code 1.79.2 (user setup)
Extensions : 
C#
C# DevKit

dotnet --info
.NET SDK:
 Version:   7.0.107
 Commit:    bf72c06963
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.107\
Host:
  Version:      7.0.7
  Architecture: x64
  Commit:       5b20af47d9
.NET SDKs installed:
  6.0.410 [C:\Program Files\dotnet\sdk]
  7.0.107 [C:\Program Files\dotnet\sdk]
.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Error message in c# extension log:
Dotnet path: c:\Users\erikr\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.7\dotnet.exe
Activating C# + C# Dev Kit + C# IntelliCode...
Failed to load the dll from [c:\Users\erikr\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.7\host\fxr\7.0.7\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from c:\Users\erikr\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.7\host\fxr\7.0.7\hostfxr.dll failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306
[Info  - 4:53:06 PM] Connection to server got closed. Server will restart.
[Error - 4:53:06 PM] Server initialization failed.

Log in C# DevKit:
Starting Open a solution...
Starting Open a solution with environment service...
Starting Clear environment...
Starting Spawn .NET server...
.NET server started and IPC established in 1934ms
Completed Spawn .NET server (1958ms)
Completed Clear environment (2557ms)
Completed Open a solution with environment service (2847ms)
Starting Restore solution...
Completed Open a solution (3100ms)
Completed Restore solution (2203ms)

My Microsoft Account is not associated to a Visual Studio Subscription according.

**Comment by slowsigma** [comment]
Dotnet path: c:\Users\my.account\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10\dotnet.exe
Activating C# + C# Dev Kit + C# IntelliCode...
Failed to load the dll from [c:\Users\my.account\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10\host\fxr\7.0.10\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from c:\Users\my.account\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10\host\fxr\7.0.10\hostfxr.dll failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306
[Error - 10:58:01 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 10:58:01 AM] Connection to server got closed. Server will restart.
true
[Error - 10:58:01 AM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Dotnet path: c:\Users\my.account\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10\dotnet.exe
Activating C# + C# Dev Kit + C# IntelliCode...
Failed to load the dll from [c:\Users\my.account\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10\host\fxr\7.0.10\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from c:\Users\my.account\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10\host\fxr\7.0.10\hostfxr.dll failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306
[Error - 10:58:01 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 10:58:01 AM] Connection to server got closed. Server will restart.
true
[Error - 10:58:01 AM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Dotnet path: c:\Users\my.account\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10\dotnet.exe
Activating C# + C# Dev Kit + C# IntelliCode...
Failed to load the dll from [c:\Users\my.account\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10\host\fxr\7.0.10\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from c:\Users\my.account\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10\host\fxr\7.0.10\hostfxr.dll failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306
[Error - 10:58:01 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 10:58:01 AM] Connection to server got closed. Server will restart.
true
[Error - 10:58:01 AM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:58:01 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Dotnet path: c:\Users\my.account\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10\dotnet.exe
Activating C# + C# Dev Kit + C# IntelliCode...
[Error - 10:58:01 AM] Client Microsoft.CodeAnalysis.LanguageServer: connection to server is erroring. Shutting down server.
[Error - 10:58:01 AM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
	at s.shutdown (c:\Users\my.account\.vscode\extensions\ms-dotnettools.csharp-2.0.357-win32-ia32\dist\extension.js:2:2241411)
	at s.stop (c:\Users\my.account\.vscode\extensions\ms-dotnettools.csharp-2.0.357-win32-ia32\dist\extension.js:2:2240992)
	at s.stop (c:\Users\my.account\.vscode\extensions\ms-dotnettools.csharp-2.0.357-win32-ia32\dist\extension.js:2:2404164)
	at s.handleConnectionError (c:\Users\my.account\.vscode\extensions\ms-dotnettools.csharp-2.0.357-win32-ia32\dist\extension.js:2:2247499)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[Error - 10:58:01 AM] Server initialization failed.
  Message: write EPIPE
  Code: -32099 
[Error - 10:58:01 AM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
  Message: write EPIPE
  Code: -32099 
[Error - 10:58:01 AM] Restarting server failed
  Message: write EPIPE
  Code: -32099 
[Error - 10:58:01 AM] Restarting server failed
  Message: write EPIPE
  Code: -32099 
[Info  - 10:58:01 AM] Connection to server got closed. Server will restart.
true
Dotnet path: c:\Users\my.account\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10\dotnet.exe
Activating C# + C# Dev Kit + C# IntelliCode...
Failed to load the dll from [c:\Users\my.account\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10\host\fxr\7.0.10\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from c:\Users\my.account\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10\host\fxr\7.0.10\hostfxr.dll failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306
Failed to load the dll from [c:\Users\my.account\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10\host\fxr\7.0.10\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from c:\Users\my.account\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10\host\fxr\7.0.10\hostfxr.dll failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306
[Error - 10:58:01 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 10:58:01 AM] The Microsoft.CodeAnalysis.LanguageServer server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 10:58:01 AM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 

Me Too.
