### ISSUE TITLE
v2 of C# extension breaks debugger (Couldn't find a debug adapter descriptor for debug type 'coreclr')

### ISSUE THREAD

**Issue by Gilleece** [dotnet/vscode-csharp#6030]
## Issue Description ##

Cannot debug since v2 update. Trying to do so gives the error "Couldn't find a debug adapter descriptor for debug type 'coreclr' (extension might have failed to activate).

This is within a dev container based on ubuntu 22.04. Reverting back to c# 1.26 extension resolves the issue. Tested on both insiders and release vs code.

## Environment information ##

**VSCode version**: 1.81.0-insider
**C# Extension**: 2.0.320

<details><summary>Mono Information</summary>
        There is a problem with running OmniSharp on mono: Error: Unable to find Mono. Ensure that Mono's '/bin' folder is added to your environment's PATH variable.</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.412
 Commit:    ee124f7fe1

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.412/

global.json file:
  Not found

Host:
  Version:      6.0.20
  Architecture: x64
  Commit:       a08d9ce2ca

.NET SDKs installed:
  6.0.412 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.20 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.20 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|cmake|twxs|0.0.17|
|cmake-tools|ms-vscode|1.14.34|
|cpptools|ms-vscode|1.16.3|
|cpptools-extension-pack|ms-vscode|1.3.0|
|csharp|ms-dotnettools|2.0.320|
|gitlens|eamodio|14.1.1|
|python|ms-python|2023.14.0|
|vscode-catch2-test-adapter|matepek|4.5.1|
|vscode-docker|ms-azuretools|1.26.0|
|vscode-dotnet-runtime|ms-dotnettools|1.6.0|
|vscode-pull-request-github|GitHub|0.70.0|
|vscode-pylance|ms-python|2023.8.10|;

</details>

**Comment by WardenGnaw** [comment]
@Gilleece When starting up VS Code, can you go to the output pane and share the logs in the C# pane?
![image](https://github.com/dotnet/vscode-csharp/assets/3953714/3fbd54d2-d17a-4442-a4cb-bed31bc5b4bd)

**Comment by Gilleece** [comment]
@WardenGnaw Hi Andrew, C# doesn't show up in the list of outputs for me. For reference it's running within a docker container, I tried there with the latest version 2.0.328 and still the same issue, have reverted back to 1.26 again. If there's any other way I can get logs please let me know. Thanks.

**Comment by WardenGnaw** [comment]
`C#` should be one of the output panes that gets created when the extension activates.

Couple things that could help me investigate:
1. There should be an `Extension Host` output pane, can you share those logs? Could you also make sure the `Developer Log Level` is set to `info`? `trace` would be better. You can change this with the command pallete and looking for `Developer Set Log Level`
![image](https://github.com/dotnet/vscode-csharp/assets/3953714/564afc3d-244c-4028-9382-cc9a46c52abd)

1. What is the base image of the container you are trying to connect to so I could try reproducing this on my side.
1. What extensions are installed in the docker container since the `Visual Studio Code Extensions` show the one from the local VS Code isntance instead of the vscode-docker extension connection.

**Comment by Gilleece** [comment]
@WardenGnaw Could the issue be that the extension isn't properly activating? It would be inline with the original error I mentioned popping up ("Couldn't find a debug adapter descriptor for debug type 'coreclr' (extension might have failed to activate)).

1. Local log: https://pastebin.com/6VDhki08
    Remote log (probably more useful): https://pastebin.com/nL1pAd8F
 
    Seems like the most relevant part there is that the extension is failing to activate:
    
    `2023-08-08 08:30:32.907 [error] Activating extension ms-dotnettools.csharp failed due to an error:
2023-08-08 08:30:32.907 [error] CodeExpectedError: Unable to write into workspace settings. Please open the workspace settings to correct errors/warnings in the file and try again.
    at v.y (vscode-file://vscode-app/snap/code-insiders/1374/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2277:45391)
    at v.o (vscode-file://vscode-app/snap/code-insiders/1374/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2277:42752)
    at v.n (vscode-file://vscode-app/snap/code-insiders/1374/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2277:42643)
    at async Object.factory (vscode-file://vscode-app/snap/code-insiders/1374/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2277:42393)`


2. I can't share the base image unfortunately as it's private, unless I am misunderstanding the request. The image is built on ubuntu 22.04, if that is of any use.

3. The installed extensions within the container are:

- .Net
- C/C++
- C/C++ Extension pack
- C#
-  C++ TestMate
- CMake
- CMake Tools
- Docker
- Github Pull Requests and Issues
- GitLens
- Pylance
- Python
- C/C++ Themes

Thanks for your time btw, much appreciated. I am still work fine right now with 1.26 without issue but if this was resolved then it would be ideal to not need to remain on an older version. Thanks again.

**Comment by fxcosta** [comment]
Same issue, still not identified one reason, but i have a similar env: dotnet running inside docker and vscode connecting in wsl :(

**Comment by WardenGnaw** [comment]
> then it would be ideal to not need to remain on an older version

Thank you for following up and helping us trying to resolve your issue. We would love to get to the root cause of this and let you work on the latest version.

> Could the issue be that the extension isn't properly activating? 
...
Seems like the most relevant part there is that the extension is failing to activate:
2023-08-08 08:30:32.907 [error] Activating extension ms-dotnettools.csharp failed due to an error: 2023-08-08 08:30:32.907 [error] CodeExpectedError: Unable to write into workspace settings. Please open the workspace settings to correct errors/warnings in the file and try again. at v.y (vscode-file://vscode-app/snap/code-insiders/1374/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2277:45391) at v.o (vscode-file://vscode-app/snap/code-insiders/1374/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2277:42752) at v.n (vscode-file://vscode-app/snap/code-insiders/1374/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2277:42643) at async Object.factory (vscode-file://vscode-app/snap/code-insiders/1374/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2277:42393)

I agree. Seems like an issue hiding the real problem. Let me recreate your scenario and see if I can get the same error.

For 2, I was wondering if you were building on top of the [Ubuntu 22.04 .NET Containers](https://hub.docker.com/_/microsoft-dotnet-sdk/), but I'll try from a [basic Ubuntu container](https://hub.docker.com/_/ubuntu/).

**Comment by dibarbet** [comment]
Seems like there might be some errors in your settings.json file.  Would you be to share your settings file?  There's probably a bug here where an invalid settings file is causing the extension to fail which I'll take a look at.

**Comment by gavinlefebvre** [comment]
I had the same issues. I deleted all the references to `"omnisharp*"` from my `settings.json` & now at least C# showed up in output (but failed with a different error, I think due to Roslyn missing). HOWEVER making those changes suddenly caused vs-code to red-squig a syntax error in `settings.json` (a line ended in a comma, but it was at the end of an inline comment). After inserting a comma before the comment, things are now working with all the `"omnisharp*"` properties back in place.

Semi-related, but using the "Docker: Intialize for Docker debugging" will strip any comments out of `launch.json` and `tasks.json` which isn't fun if you'd like to share the "why" behind various whatever with your future teammates.

JSON comments. Can we just allow & ignore?

**Comment by Gilleece** [comment]
@gavinlefebvre I can confirm this was my issue. The settings.json had a comma missing before a comment, which on 1.26 was fine but in 2.xx was stopping the extension from launching. I understand that the lack of a comma is an error on the developers part, but probably worth noting that this is a difference now.

Thanks to all for their help here, much appreciated.

**Comment by she2122** [comment]
json
