### ISSUE TITLE
Launch debug error (Couldn't find a debug adapter descriptor for debug type 'dotnet')

### ISSUE THREAD

**Issue by mcm-ham** [dotnet/vscode-csharp#6562]
Type: <b>Bug</b>

Launch configuration works fine in launch.json:

```json
{
  "name": "C#: WebApp Debug",
  "projectPath": "${workspaceFolder}/WebApp.csproj",
  "request": "launch",
  "type": "dotnet"
}
```

But when placed in workspace file under "launch" I get the `Couldn't find a debug adapter descriptor for debug type 'dotnet'` error. The launch & task configuration that gets generated from older version of extension still works in workspace file.

Similar https://github.com/dotnet/vscode-csharp/issues/6030

Extension version: 2.6.24
VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:57:32.750Z)
OS version: Darwin arm64 23.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|12, 17, 11|
|Memory (System)|8.00GB (0.15GB free)|
|Process Argv|--crash-reporter-id bfcf6f59-63c2-4c83-bfc4-61465df520ff|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30856252
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
962ge761:30841074
a2ce3375:30757347
7ij38806:30736111
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingc:30859502
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
pythonmhint1:30842940
dsvsc015:30845448
pyreplss1:30858575
pythonmypyd1cf:30859727
pythontbext0:30864172

```

</details>

**Comment by gregg-miskelly** [comment]
@mcm-ham what that error means is that VS Code was unable to communicate with the C# extension.

Questions:
1. A new release of the C# extension came out today. If you update, does it still repro? I doubt anything in the new version fixed it, but maybe just installing another version will help.
2. If it doesn't, do you see a 'C#' output window tab? If so, can you past whatever it shows there?

**Comment by mcm-ham** [comment]
1. Just updated to v2.7.25 no difference.
2. Yes I do, here's the output after attempting to debug:
```
Using dotnet configured on PATH
Dotnet path: /usr/local/share/dotnet/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
waiting for named pipe information from server...
[stdout] {"pipeName":"/var/folders/dp/880w89hd4tx80d3s82y0c9y40000gn/T/908ef81b-265c-4b6e-844c-100ef1f9e34e.sock"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 10:43:44] [Program] Language server initialized
```

**Comment by gregg-miskelly** [comment]
Very strange. If you clone this repo locally and follow [these instructions](https://github.com/dotnet/vscode-csharp/blob/main/CONTRIBUTING.md#build-and-run-the-extension) to run the experimental instance, does this issue reproduce for you in the experimental instance?

If it does reproduce under the experimental instance, and you have the time to debug it, [here](https://github.com/dotnet/vscode-csharp/blob/e336406b01c0824af748931c8e0ca5434d0363a2/src/lsptoolshost/debugger.ts#L47) is where the `dotnet` debugger type should be getting registered. That function (`registerDebugger`) is called from [activateRoslynLanguageServer](https://github.com/dotnet/vscode-csharp/blob/e336406b01c0824af748931c8e0ca5434d0363a2/src/lsptoolshost/roslynLanguageServer.ts#L873), which I can see from your tracing is called.

**Comment by Sujay-WSD** [comment]
@gregg-miskelly  i am getting 2023-11-13 14:13:12.405 [error] Activating extension ms-dotnettools.csharp failed due to an error:
2023-11-13 14:13:12.405 [error] c:\Users\skanolkar\.vscode\extensions\ms-dotnettools.csharp-2.10.28-win32-x64\dist\extension.js:1
(function (exports, require, module, __filename, __dirname) { this erro while starting debugger

**Comment by gregg-miskelly** [comment]
@Sujay-WSD did the error you saw have any additional information? That error message looks truncated and doesn't really tell me anything.

**Comment by Sujay-WSD** [comment]
Here is complete log of errror:

2023-11-13 14:13:12.405 [error] Activating extension ms-dotnettools.csharp failed due to an error: 2023-11-13 14:13:12.405 [error] c:\Users\skanolkar\.vscode\extensions\ms-dotnettools.csharp-2.10.28-win32-x64\dist\extension.js:1 (function (exports, require, module, __filename, __dirname) {                                                                 SyntaxError: Invalid or unexpected token     at new Script (node:vm:100:7)     at Module.o._compile (c:\Users\skanolkar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1131)     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1371:10)     at Module.load (node:internal/modules/cjs/loader:1171:32)     at Module._load (node:internal/modules/cjs/loader:1012:12)     at Function.f._load (node:electron/js2c/asar_bundle:2:13377)     at Function.r._load (c:\Users\skanolkar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:5647)     at Function.c._load (c:\Users\skanolkar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:29431)     at Function.t._load (c:\Users\skanolkar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:35262)     at Module.require (node:internal/modules/cjs/loader:1195:19)     at require (node:internal/modules/cjs/helpers:110:18)     at Function.i [as __$__nodeRequire] (c:\Users\skanolkar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:5:98)     at h.vb (c:\Users\skanolkar\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:30610)     at async Promise.all (index
________________________________
From: Gregg Miskelly ***@***.***>
Sent: Tuesday, November 14, 2023 3:15 AM
To: dotnet/vscode-csharp ***@***.***>
Cc: Sujay Kanolkar ***@***.***>; Mention ***@***.***>
Subject: [ EXTERNAL ] Re: [dotnet/vscode-csharp] Launch debug error (Couldn't find a debug adapter descriptor for debug type 'dotnet') (Issue #6562)


@Sujay-WSD<https://link.edgepilot.com/s/0b0e2629/sZ-Q6WbyTEetjdT07JYHQQ?u=https://github.com/Sujay-WSD> did the error you saw have any additional information? That error message looks truncated and doesn't really tell me anything.

**Comment by dibarbet** [comment]
@Sujay-WSD apologies for the late reply, are you still having issues on the latest versions of the extensions?  If so can you post the most up to date logs?

**Comment by gregg-miskelly** [comment]
Closing old issue. Feel free to ping or open a new issue if you are still experiencing this.
