### ISSUE TITLE
VS Code Debug can not be run in new version extension C# From v2.10.28

### ISSUE THREAD

**Issue by tokkn** [dotnet/vscode-csharp#6707]
In vs code, When I updated C# extension to v2.10.28, the debug can not be run.

`Message: Couldn't find a debug adapter descriptor for debug type 'coreclr'(extension might have failed to activate)`

But when I return to v2.9.20, it can ben run successful. 
The last version v2.12.19 is also not work. 
Is there any necessary setting changed?

## Environment data
```
   "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch (web)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",

```

**Comment by nanangp** [comment]
Try checking the different logs mentioned in #6030 to see if they have any hints on what may be causing the Extension to fail to activate.

**Comment by JoeRobich** [comment]
@dibarbet TelemetryLogger api was [finalized in 1.75.0](https://code.visualstudio.com/updates/v1_75#_telemetry). Since Razor is using the vscode-extension-telementry packages, which in turn uses this API, should the minimum supported VS Code get bumped [here](https://github.com/dotnet/vscode-csharp/blob/0b41c68a72d6cfa38fee23f1ede805f9e9774520/package.json#L1017)?

**Comment by dibarbet** [comment]
> @dibarbet TelemetryLogger api was [finalized in 1.75.0](https://code.visualstudio.com/updates/v1_75#_telemetry). Since Razor is using the vscode-extension-telementry packages, which in turn uses this API, should the minimum supported VS Code get bumped [here](https://github.com/dotnet/vscode-csharp/blob/0b41c68a72d6cfa38fee23f1ede805f9e9774520/package.json#L1017)?

I thought we already bumped it to some 1.8x version, but I guess not.  I'll take care of that.  Thanks!
