### ISSUE TITLE
i want disable ... in varriable

### ISSUE THREAD

**Issue by NCLnclNCL** [dotnet/vscode-csharp#6709]
it like ...
![clipimage](https://github.com/dotnet/vscode-csharp/assets/126905141/fdb2dcaf-582d-4d03-8fb7-34e1ee671833)

**Comment by dibarbet** [comment]
The `...` under the variable name means you have an information level diagnostic at that location.  I don't know exactly what diagnostic is being triggered there, but in general you have two options:
1.  Fix the issue causing the diagnostic to be triggered. 
2.  Configure the severity of the diagnostic to silent so that the diagnostic does not show up in VSCode using an .editorconfig file.  See https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-files#editorconfig and https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-style-rule-options
