### ISSUE TITLE
Multiple Errors Appear When Creating a C# Text File

### ISSUE THREAD

**Issue by SlyCoop91** [dotnet/vscode-csharp#6973]
Type: <b>Bug</b>

Issue Description
When creating a C# text file with the extension installed on Visual Studio Code, three errors pop up:
   Request textDocument/inlayHint failed.
   Request textDocument/codeAction failed.
   Request textDocument/diagnostic failed.

C# Log
[Error - 8:01:11 PM] Request textDocument/diagnostic failed.
  Message: Unsupported extension '' and LSP language id ''
  Code: -32000 
[object Object]
[Error - 8:01:11 PM] Document pull failed for text document untitled:Untitled-1
  Message: Unsupported extension '' and LSP language id ''
  Code: -32000 
[object Object]
[Error - 8:01:11 PM] Request textDocument/codeAction failed.
  Message: Unsupported extension '' and LSP language id ''
  Code: -32000 
[object Object]
[Error - 8:01:11 PM] Request textDocument/inlayHint failed.
  Message: Unsupported extension '' and LSP language id ''
  Code: -32000 
[object Object]

Steps
1. Click "New Text File" in File tab.
2. Click "Select a language".
3. Choose the "C#" to create the file.

Expected Results
Nothing.

Actual Results
Three errors pop up.

Extension version: 2.22.3
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 7840HS w/ Radeon 780M Graphics      (16 x 3793)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.19GB (6.03GB free)|
|Process Argv|--crash-reporter-id 3504a287-36f3-44f0-8bb2-9484d8cc1261|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30986171
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:30979542
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
dsvsc020:30976470
7ghi1836:30988842

```

</details>

**Comment by JoeRobich** [comment]
Interesting. Setting the language to C# makes the extension aware of the file but since it hasn't been saved it doesn't have an extension. Note that since it hasn't been saved it won't be associated with a particular project, meaning it may not have all the references you may want.

As a workaround you can use the file explorer to save a new empty file in your open folder.

**Comment by SlyCoop91** [comment]
First of all, how do I go about doing the workaround you mentioned?  I am actually just starting to use Visual Studio Code, so I am not knowledgeable of how to do it.

Secondly, do you think it is possible for the developers to fix the cause of the errors?  I know it has something to do with the extension because it doesn't happen when I create a new text file using the C or the C++ extensions?

**Comment by JoeRobich** [comment]
> First of all, how do I go about doing the workaround you mentioned?

After you have opened a folder in VS Code, you will see buttons in the title bar of the file explorer when your mouse is hovering over it.

![Image](https://github.com/dotnet/vscode-csharp/assets/611219/0d94331f-2c6e-400b-bdba-b1b0e012a712)

Also, if your folder contains subfolders, then you can right click on a subfolder and there will be a "New File..." option.

![Image](https://github.com/dotnet/vscode-csharp/assets/611219/37feb23a-92df-4213-91c8-c04ecbdc7f0a)

> Secondly, do you think it is possible for the developers to fix the cause of the errors?

Yes, I think this issue is fixable but it may not be a high priority. There is still the caveat that until the file is saved it won't be associated with a particular project. This means, that if you had added references to NuGet packages to your project, they will not be available within the file until it has been saved.

**Comment by SlyCoop91** [comment]
I see the "New File..." after opening a folder.  Do I just click it, and if I do that, what is the next thing to do?

**Comment by qvikuku** [comment]
This is not limited to unsaved text files.

E.g. opening a staged file in source control bar gives the following:
```
[Error - 13:57:57] Request textDocument/diagnostic failed.
  Message: Unsupported extension '.cs%22,%22ref%22:%22%22%7D' and LSP language id ''
  Code: -32000 
[object Object]
[Error - 13:57:57] Document pull failed for text document git:/my_path/myfile.cs?%7B%22path%22%3A%22%2Fmy_path%2Fmyfile.cs%22%2C%22ref%22%3A%22%22%7D
  Message: Unsupported extension '.cs%22,%22ref%22:%22%22%7D' and LSP language id ''
  Code: -32000 
[object Object]
```

(Note that I masked the path of the opened file, including the url encoded part.)

I've been getting these for roughly "few weeks" now. Annoying popups, but otherwise harmless.

I'm not familiar with inner workings of Visual Studio Code or language servers, so the following is conjecture, but this smells like a more general problem of this extension erroring out when it's touching bunch of things that it's not supposed to be touching and then turning it into a user problem. E.g. seems to me new text file sand staged C# files in some git temporary folder don't need much more language specific processing from extenstions than some basic syntax highlighting.

**Comment by chickenSandwich** [comment]
This happens every time I stage `.cs` files:

```
Request textDocument/diagnostic failed.
  Message: Unsupported extension '.cs%22,%22ref%22:%22%22%7D' and LSP language id ''
  Code: -32000 
[object Object]
```

**Comment by ltouro** [comment]
Same here

> This happens every time I stage `.cs` files:
> 
> ```
> Request textDocument/diagnostic failed.
>   Message: Unsupported extension '.cs%22,%22ref%22:%22%22%7D' and LSP language id ''
>   Code: -32000 
> [object Object]
> ```

**Comment by ltouro** [comment]
Can't even disable this type of error 
![image](https://github.com/dotnet/vscode-csharp/assets/5283919/07dd3295-eaa5-44d0-858f-e1202881e167)

**Comment by aflordelis** [comment]
> Same here
> 
> > This happens every time I stage `.cs` files:
> > ```
> > Request textDocument/diagnostic failed.
> >   Message: Unsupported extension '.cs%22,%22ref%22:%22%22%7D' and LSP language id ''
> >   Code: -32000 
> > [object Object]
> > ```
> 
> Edit: Was able to fix that updating SDK version (8.0.302) and removing the older version (8.0.100)

Currently using 8.0.302 but the issue still persists.
The popups are so annoying.

**Comment by ltouro** [comment]
> > Same here
> > > This happens every time I stage `.cs` files:
> > > ```
> > > Request textDocument/diagnostic failed.
> > >   Message: Unsupported extension '.cs%22,%22ref%22:%22%22%7D' and LSP language id ''
> > >   Code: -32000 
> > > [object Object]
> > > ```
> > 
> > 
> > Edit: Was able to fix that updating SDK version (8.0.302) and removing the older version (8.0.100)
> 
> Currently using 8.0.302 but the issue still persists. The popups are so annoying.

Have you checked the installed SDK list? Make sure you don't have more versions for 8.X available (or maybe not any version at all, if big Visual Studio is not a thing for you). To that end, I suggest usinghttps://learn.microsoft.com/en-us/dotnet/core/additional-tools/uninstall-tool

**Comment by dibarbet** [comment]
FYI a fix is in progress for this and should be available this month.  In the meantime, you can check the following setting in VSCode to suppress the error messages:
![image](https://github.com/dotnet/vscode-csharp/assets/5749229/a0848942-5005-4cfc-9782-a286c3c01136)

**Comment by aflordelis** [comment]
> FYI a fix is in progress for this and should be available this month. In the meantime, you can check the following setting in VSCode to suppress the error messages: ![image](https://private-user-images.githubusercontent.com/5749229/346767173-a0848942-5005-4cfc-9782-a286c3c01136.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0OTE0NTQsIm5iZiI6MTcyMDQ5MTE1NCwicGF0aCI6Ii81NzQ5MjI5LzM0Njc2NzE3My1hMDg0ODk0Mi01MDA1LTRjZmMtOTc4Mi1hMjg2YzNjMDExMzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDlUMDIxMjM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjlmNGIwMmUxZTg1MGYxZWMwYzAxN2IwODNkNGJjNzUxODM4NWY4ZmRjZDAyZWY1ZDE1MDM1N2VlNTE1MGQxOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.r42VVcKveAzX34QAwX43H04Q_53WG4f0ZQX8edxJ6pg)

Awesome, this worked!! Thanks.

**Comment by dibarbet** [comment]
The fix for this should make it into next week's prerelease

**Comment by dibarbet** [comment]
This should be fixed (at least for new C# files / diff window files) in the 2.39.28 prerelease version of the C# extension
